# Generated by Django 5.0.6 on 2024-05-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboutus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutus",
            name="description",
            field=models.TextField(max_length=10000),
        ),
    ]
