# Generated by Django 5.0.6 on 2024-05-09 15:14

import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        storage=gdstorage.storage.GoogleDriveStorage,
                        upload_to="Carousel",
                    ),
                ),
            ],
        ),
    ]
