# Generated by Django 5.0.6 on 2024-05-09 16:55

import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        storage=gdstorage.storage.GoogleDriveStorage, upload_to="File"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="carousel",
            name="files",
            field=models.ManyToManyField(blank=True, to="home.file"),
        ),
    ]
