# Generated by Django 5.0.6 on 2024-05-10 09:02

import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_file_carousel_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carousel",
            name="files",
        ),
        migrations.RemoveField(
            model_name="carousel",
            name="title",
        ),
        migrations.AlterField(
            model_name="carousel",
            name="image",
            field=models.ImageField(
                storage=gdstorage.storage.GoogleDriveStorage(), upload_to="Carousel"
            ),
        ),
        migrations.DeleteModel(
            name="File",
        ),
    ]
