# Generated by Django 5.0.6 on 2024-05-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_carousel_files_remove_carousel_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carousel",
            name="image",
            field=models.FileField(upload_to="home/carousel/"),
        ),
    ]
