# Generated by Django 5.0.6 on 2024-05-17 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_carousel_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("time", models.TimeField()),
                ("description", models.TextField(blank=True)),
                ("image", models.FileField(blank=True, upload_to="home/prayer/")),
            ],
        ),
        migrations.CreateModel(
            name="WorshipPlaces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="home/worshipPlace/"),
                ),
                (
                    "places",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.prayer"
                    ),
                ),
            ],
        ),
    ]
