# Generated by Django 5.0.6 on 2024-05-20 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_prayer_worshipplaces"),
    ]

    operations = [
        migrations.RenameField(
            model_name="worshipplaces",
            old_name="places",
            new_name="prayers",
        ),
    ]
