# Generated by Django 5.0.6 on 2024-05-20 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_rename_places_worshipplaces_prayers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worshipplaces",
            name="prayers",
        ),
        migrations.AddField(
            model_name="prayer",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="home.worshipplaces",
            ),
        ),
    ]
