# Generated by Django 5.0.6 on 2024-05-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_remove_worshipplaces_prayers_prayer_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prayer",
            name="day",
            field=models.TextField(max_length=15),
        ),
    ]
