# Generated by Django 5.0.6 on 2024-05-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_prayer_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prayer",
            name="image",
        ),
    ]
