# Generated by Django 5.0.6 on 2024-05-20 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_remove_prayer_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prayer",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.worshipplaces",
            ),
        ),
    ]
