# Generated by Django 5.0.6 on 2024-05-20 15:07

import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_prayer_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="Magazine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("month", models.TextField(max_length=100)),
                ("image", models.ImageField(upload_to="home/magazine/")),
                (
                    "download_url",
                    models.FileField(upload_to=gdstorage.storage.GoogleDriveStorage()),
                ),
            ],
        ),
    ]
