# Generated by Django 5.0.6 on 2024-05-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_magazine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magazine",
            name="download_url",
            field=models.FileField(upload_to="gd_storage"),
        ),
    ]
