# Generated by Django 5.0.6 on 2024-05-20 15:13

import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_magazine_download_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magazine",
            name="download_url",
            field=models.FileField(
                storage=gdstorage.storage.GoogleDriveStorage(), upload_to="magazines"
            ),
        ),
    ]
