# Generated by Django 5.0.6 on 2024-05-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_magazine_download_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prayer",
            name="time",
            field=models.TextField(max_length=20),
        ),
    ]
